version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
   configuration: docs/source/conf.py

formats:
   - epub

python:
   install:
     - requirements: requirements/readthedocs.txt
     - requirements: requirements/docs.txt
