name: Setup Python Environment
description: Setup Python with uv and cache dependencies

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.12"
  uv-version:
    description: uv version to use
    required: false
    default: "0.5.28"
  cache-dependency-path:
    description: Path to dependency files for caching
    required: false
    default: "uv.lock"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true

    - name: Setup Python
      shell: bash
      run: |
        uv python install ${{ inputs.python-version }}
        echo "Python ${{ inputs.python-version }} installed"

    - name: Sync dependencies
      shell: bash
      run: |
        uv sync --all-extras --dev
        echo "Dependencies synced"

    - name: Show environment info
      shell: bash
      run: |
        echo "Python version:"
        uv run python --version
        echo "uv version:"
        uv --version
        echo "Installed packages:"
        uv pip list