name: build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml

  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      python-versions: '["3.12", "3.13"]'
      codecov-upload: true
