name: Reusable Python Setup

on:
  workflow_call:
    inputs:
      python-version-file:
        description: "Path to file containing Python version (default: pyproject.toml)"
        required: false
        type: string
        default: "pyproject.toml"
      uv-version:
        description: "Version of uv to install"
        required: false
        type: string
        default: "latest"
      install-extras:
        description: 'Extras to install (e.g., "dev" or "all-extras")'
        required: false
        type: string
        default: "all-extras"
      fetch-depth:
        description: "Number of commits to fetch. 0 fetches all history"
        required: false
        type: number
        default: 1

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ${{ inputs.uv-version }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ${{ inputs.python-version-file }}

      - name: Install dependencies
        run: |
          if [ "${{ inputs.install-extras }}" = "all-extras" ]; then
            uv sync --all-extras
          elif [ -n "${{ inputs.install-extras }}" ]; then
            uv sync --extra ${{ inputs.install-extras }}
          else
            uv sync
          fi
