name: Reusable Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Install pre-commit hook
        run: uv run pre-commit install

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run type checking
        run: uv run pyright modules

      - name: Check docstring coverage
        run: uv run interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" --fail-under 0 modules
