name: Reusable Build

on:
  workflow_call:
    inputs:
      upload-artifact:
        description: "Whether to upload build artifacts"
        required: false
        type: boolean
        default: false
      artifact-name:
        description: "Name for the artifact"
        required: false
        type: string
        default: "dist"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build package
        run: uv build

      - name: Upload artifacts
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist/
